[project]
name = "logfortress"
version = "0.0.1"
description = "A simple debugging tool for Docker containers"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "docker>=6.1.3",
    "flask>=2.2.5",
    "texttable>=1.7.0",
]